#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -o pipefail
set -o nounset
set -o errexit

servicesWithUpdates=$(git diff --name-only --cached | grep / | sed 's/\/.*$//g' | sort | uniq)

for service in $servicesWithUpdates; do
  configFile="$service/.husky/pre-commit"
  if [[ -f "$configFile" ]]; then
    "$service"/.husky/pre-commit
  else
    echo "No hook script found at \"$configFile\""
  fi
done

exit 0
